// Piano keys 88 notes as reference
// Order of prominance:
// lowercase by frequency
// uppercase by frequency
// punctuation by frequency
// numbers 0-9
// arbitrary symbols used in English (order and choices subjective)

export default {
    // Lowercase
    'e': 'C4',
    't': 'D4',
    'a': 'B3',
    'o': 'E4',
    'i': 'A3',
    'n': 'F4',
    's': 'G3',
    'h': 'G4',
    'r': 'F3',
    'd': 'A4',
    'l': 'E3',
    'c': 'B4',
    'u': 'D3',
    'm': 'C5',
    'w': 'C3',
    'f': 'D5',
    'g': 'B2',
    'y': 'E5',
    'p': 'A2',
    'b': 'F5',
    'v': 'G2',
    'k': 'G5',
    'j': 'F2',
    'x': 'A5',
    'q': 'E2',
    'z': 'B5',
    // uppercase
    'T': 'D2',
    'A': 'C#4',
    'S': 'C2',
    'H': 'D#4',
    'W': 'Bb3',
    'I': 'F#4',
    'O': 'Ab3',
    'B': 'G#4',
    'M': 'Gb3',
    'F': 'A#4',
    'C': 'Eb3',
    'L': 'C#5',
    'D': 'Db3',
    'P': 'D#5',
    'N': 'Bb2',
    'E': 'F#5',
    'G': 'Ab2',
    'R': 'G#5',
    'Y': 'Gb2',
    'U': 'A#5',
    'V': 'Eb2',
    'J': 'C6',
    'K': 'Db2',
    'Q': 'D6',
    'Z': 'F6',
    'X': 'E6',
    // punctuation
    '.': 'G6',
    ',': 'B1',
    ';': 'A6',
    ':': 'A1',
    '!': 'B6',
    '?': 'G1',
    "'": 'C7',
    '"': 'F1',
    // numbers
    '0': 'D7',
    '1': 'E1',
    '2': 'E7',
    '3': 'D1',
    '4': 'F7',
    '5': 'C1',
    '6': 'G7',
    '7': 'B0',
    '8': 'A7',
    '9': 'A0',
    // symbols
    '(': 'B7',
    ')': 'Bb1',
    '[': 'C8',
    ']': 'Ab1',
    '{': 'C#6',
    '}': 'Gb1',
    '$': 'D#6',
    '&': 'Eb1',
    '#': 'F#6',
    '%': 'Db1',
    '*': 'G#6',
    '=': 'Bb0',
    '+': 'A#6',
    '_': 'D#7',
    '^': 'F#7',
    '~': 'G#7',
    '@': 'C#7',
    '`': 'A#7'
}
